### ISSUE TITLE
the accurary of prediction: shorter then relatives about the everage gene length

### ISSUE THREAD

**Issue by CrawlingSponge** [Jstacs/Jstacs#18]
hi, 
i conducted several mammal genomes with GeMoMa (1.7.1 version, "run.sh") without or with RNA, but the predictions of gene length more shorter than the reletives of my studied genomes.

and  i ve done a lot of tries, still cannot improve the everage length of my predicted gene? could you help me why? 

Here is how i performed the pipe:
the inputs: 1. target genome (mask or unmask, contig or chromosome level, all had tried); 2. relatives high quality assembly genome and gff annotations (gff3, all transcripts or longest transcrpts);
the run GeMoMA process: "run.sh".

seriously thanks waiting for your kind reply!

**Comment by JensKeilwagen** [comment]
Hi CrawlingSponge,

You're right mammal genomes sometimes have very large introns that lead to long genomic regions coding for a gene. GeMoMa has parameters that limit the maximum intron length. By default it is set to 15 kb, but you can enlarge this.

I would propose to use the GeMoMaPipeline directly on the command line. There we have the parameters **DenoiseIntrons.m** and **GeMoMa.m** (cf. https://www.jstacs.de/index.php/GeMoMa-Docs#GeMoMa_pipeline). Both parameters refer to a single intron and not the sum of all introns in a prediction.

- DenoiseIntrons.m filters the maximum intron length of RNA-seq based introns
- GeMoMa.m limits the maximum intron length in a prediction

If you like to run an annotation **without RNA-seq evidence**, I would use the following command line

`java -jar GeMoMa-1.8.jar CLI GeMoMaPipeline t=<target_genome> a=<ref_annotation> g=<ref_genome> GeMoMa.m=<your_value> AnnotationFinalizer.p=<prefix>`

If you like to run an annotation **with RNA-seq evidence**, I would use the following command line

`java -jar GeMoMa-1.8.jar CLI GeMoMaPipeline t=<target_genome> a=<ref_annotation> g=<ref_genome> GeMoMa.m=<your_value> r=MAPPED ERE.m=<mapped_RNA-seq_data> DenoiseIntrons.m=<your_value> AnnotationFinalizer.p=<prefix>`

However, we have seen that large introns are very sheldom and the size of most introns is still short. A huge maixim intron length for the predition might lead to a correct prediction of some gens, but at the same time migh lead to several wrong predictions due to too large introns size. One could imagine that the intron length of a gene is also evolutionary conserved - at least to a certain degree. For this reason, we have implemented an additional parameter **GeMoMa.sil** which allows to switch between static and dynamic intron length. Static intron length is a fixed maximum intron length for all introns (which is default in GeMoMa). Dynamic intron length depends on the intron length in the reference organism plus some overhead. You can change to dynamic intron length by using `GeMoMa.sil=false` in cour command line.

(BTW. this parameter is the reason why we have two different parameters **DenoiseIntrons.m** and **GeMoMa.m** as mentioned above.)

I hope that helps. Feel free to play around ;)

best regards, Jens

**Comment by JensKeilwagen** [comment]
Maybe one additional remark: if we talk about gene length, do you include UTRs? If so GeMoMa is only able to predict UTRs if RNA-seq evidence is given. The quality of the UTR prediction depends on the quality of the RNA-seq evidence.
GeMoMas main focus is CDS.

**Comment by CrawlingSponge** [comment]
Thanks for  your quick reply!

And i wanna repeat the last paragraph i want to express. 
here is process how i performed the prediction with an example of an Rodents genome. 
I predicted my own assembled genome, with its relatives, like mouse genome and the annotation of gff3 whithout RNA-seq. With the final prediction of GeMoMA, i did the distributions of the predictions genes with Glean compared with mouse, and both of their everage length of intron and gene are nearly half about the length of everage of intron and gene. 

Here is the paste from their distributions
mouse:
the total number of gene is 22173
the average of mRNA_length is 47511.4535245569
the average of cds_length is 1582.33748252379
the average of exon_number is 8.75398006584585
the average of exon_length is 180.756349754253
the average of intron_length is 4678.64662157053
the average of intron_length is 5923.29560458096

my_own_species_predicted_by_genome:
the total number of gene is 19449
the average of mRNA_length is 1
the average of cds_length is 1454.05861483881
the average of exon_number is 8.11625276363823
the average of exon_length is 179.153934356648
the average of intron_length is 2233.0091832606

**Comment by CrawlingSponge** [comment]
Thanks for  your quick reply!

And i wanna repeat the last paragraph i want to express. 
here is process how i performed the prediction with an example of an Rodents genome. 
I predicted my own assembled genome, with its relatives, like mouse genome and the annotation of gff3 whithout RNA-seq. With the final prediction of GeMoMA, i did the distributions of the predictions genes with Glean compared with mouse, and both of their everage length of intron and gene are nearly half about the length of everage of intron and gene. 

Here is the paste from their distributions
mouse:
the total number of gene is 22173
the average of mRNA_length is 47511.4535245569
the average of cds_length is 1582.33748252379
the average of exon_number is 8.75398006584585
the average of exon_length is 180.756349754253
the average of intron_length is 4678.64662157053
the average of intron_length is 5923.29560458096

my_own_species_predicted_by_genome:
the total number of gene is 31525
the average of mRNA_length is 14193.1838858049
the average of cds_length is 1361.67816019033
the average of exon_number is 7.03283108643933
the average of exon_length is 193.617356005593
the average of intron_length is 2126.94596314115
the average of intron_length is 2126.94596314115
