### ISSUE TITLE
"does not match the regular expression for sequence IDs" 

### ISSUE THREAD

**Issue by schraderL** [Jstacs/Jstacs#33]
Hi!

I am trying to run GeMoMa using some gffs from NCBI as reference. It looks like my run fails, because one (or more) of the genes does not comply with a GeMoMa naming convention: 

```
java.lang.IllegalArgumentException: Sequence ID (gene-Su(var)3-9_0) in fasta comment line (>gene-Su(var)3-9_0) does not match the regular expression for sequence IDs (([a-zA-Z\-\.:0-9]+(_\d+)?)|([a-zA-Z\-_\.:0-9]+_\d+)) 
```

How can I avoid this? I would prefer not having to change the gff from NCBI. Or am I missing the point and something else is going wrong?

**Comment by JensKeilwagen** [comment]
Hi Lukas,

I'm sorry the exception is thrown because the gene does not match the naming convention. In the current version, there is no workaround. The easiest thing is to rename the gene. I think the brackets are the problem.

I could adjust the the regex pattern for the next GeMoMa version allowing to use brackets.

Checking the sequence ID is important, because some letters or combinations are forbidden. They would lead to problems in the GFF or while the algorithm, for instance ";" and "\"".

best regards, Jens

**Comment by JensKeilwagen** [comment]
Hi Lukas,
I checked the code. It already has been changed since last version:
https://github.com/Jstacs/Jstacs/blob/master/projects/gemoma/Tools.java#L610

I will again slightly change this and release it with the next version.
Hence, the next version should work without renaming.

best regards, Jens

**Comment by nmflack** [comment]
I got this same error and have to start over on a massive GeMoMaPipeline run in "pre-extracted" mode. I'm using version 1.9 of the conda package with protein FASTAs downloaded from NCBI.

I don't know exactly how things work internally. But, neither the old regex nor the new regex you linked here on July 8 allow typical NCBI protein IDs because of the underscore (XP_047679166.1). 

If I change the IDs and restart my run, I get a "Null Pointer" error, because MMSeqs parses the underscore just fine and doesn't recognize the ID without it. Maybe there's a way to edit the mmseqsdbs and restart but I have seven mammalian references, and MMSeqs seems to spread the ID across multiple DB sub-files.

Why does the regex still exclude such a common ID format? I didn't have this issue running in "own" mode with NCBI GFFs and FASTAs on version 1.8 several months ago, so I'm going to try that. I'm sure there is a good reason; posting as an FYI in case others are running into the same issue.

**Comment by JensKeilwagen** [comment]
Hi Nicole,

thanks a lot for your interest in GeMoMa. I'm sorry that you have problems. Unfortunately, it's hard for me to give good advices having few information. It would be great if you could send the command line, some information about the input data and the output including the error messages. At best you could provide a small toy example that throws the same Exception.

Currently, I can only state that I work frequently with NCBI files and don't have problems. If you use pre-extracted data, what exactly do you use:
1) cds parts and assignment file
2) protein file
...
?

Second point was related to '"U" not being in the defined alphabet'. U is neither included in the DNA nor in the protein alphabet. Due to missing information, I can currently not state where the Exception is thrown. If you use the Extractor, you should not obtain U in you protein or CDS parts. If the U is for any reason in the search result, we implemented the parameter "replace unknown" (ru or GeMoMa.ru, cf. http://www.jstacs.de/index.php/GeMoMa-Docs) that replaces unknown letters by X.

I hope this can already help you a bit. Looking forward to some more information.

best regards, Jens
