### ISSUE TITLE
usage about the parameter of weight (w) 

### ISSUE THREAD

**Issue by CrawlingSponge** [Jstacs/Jstacs#36]
Hi, Jens,
after the prediction by the step of "GeMoMa" with several relative genomes, i need perform the step of "GAF" and i also strictly set the GAF.f with "iAA>=0.8 and ce/rce==1", etc, and the prediction is much better than that before this filter step.

Here is the problem, since the predicted gene supported by several predictions from the relatives, and i wanna choose the most close one as the final prediction, while others as the alternative ones. 

I tried to use the parameter of "w" to do the filter, and the relatives with different weights consindering of their phylogentic relationships. for example, the very close one with the largest weights, say, 1000.0, while the not close one we set the weight of 1.0. after than, i thought the GAF should choose the prediction with the priority  of the weight i earlier set. Is the parameter of "sumWeight (the sum of the weights of the references that perfectly support this prediction)" was used to perform this function.

yours, sincerely

supplementary files.
This is the predictions with the relative genes SP1, SP2, SP3, SP4.
![image](https://user-images.githubusercontent.com/22827591/185278895-61d20991-d398-4517-8ef1-23261ae813df.png)
this file includes the different weights considering of their phylogentic relationships (SP1, SP2, SP3, SP4)
![image](https://user-images.githubusercontent.com/22827591/185279043-d2f93366-98d4-4de8-9862-09c3671d9c03.png)
the prediction best prediction should from SP1 not from SP2, but the GAF step keep the best prediction is SP2, and the SP1, SP3, SP4 as the alternative ones.

Here is the parameter of "w" from GeMoMa website,
![image](https://user-images.githubusercontent.com/22827591/185278011-6d26566c-2afe-4e19-bac2-dd2136031481.png)

i conduct the filter like this, firstly, add the weights of each predictions like the upper step, then, i combined all the predictions to filter with sumWeight (here i dont know how to use this to get my purpose)
![image](https://user-images.githubusercontent.com/22827591/185280949-5d1ddefb-3411-47c7-b4da-9fe5c9269ebb.png)

**Comment by JensKeilwagen** [comment]
Hi,

Thanks for that interesting question. However, the question is not completely clear to me. I try to explain what GAF does and try to give an option how to get a workaround.

If I understood it correctly, your situation is the following: A prediction is perfectly supported by several reference species. You like to choose a prediction from the reference species with the smallest phylogenetic distance as representative (ref-gene) and list the remaining predictions in alternatives.

However, GAF does not use weights or any other phylogenetic information at the step of removing redundant predictions. The current implementation uses the score and the ID to determine the representative:
https://github.com/Jstacs/Jstacs/blob/65a454d228c241a759b0a9409819dba89f1448a6/projects/gemoma/GeMoMaAnnotationFilter.java#L531-L549
The attributes (e.g. score, iAA, ...) of the representative are later used to sort and select the predictions.

This implementation is based on the assumption that the GeMoMa score is a good indicator whether a prediction is valid or not. To a certain extend the score reflects how good the conservation is. The ID is used to avoid different results based due to multi-threading. (If several predictions are identical (based on the exon-intron-structure) and have same score, the last prediction would be used if ID would be ignore. Different number of threads can have an influence on the order of the predictions. To avoid this, we use the ID to get the same results no matter how many threads were used.)

From the lines of code it become clear that score is the main feature to select the representative. This seems to be reasonable for me. I'll try to give an example. Let's assume you have identical predictions from all reference species, i.e., the exon-intron structure is identical for all these prediction, but they differ in the score (=conservation). Despite having the same structure, the amino acid conservation can differ substantially. Although the conservation should be higher in phylogenetic closer related species on average, this must not be true for every gene. Especially if you're thinking about introgressions from wild species. For this reason, a prediction from the reference species with smallest phylogenetic distance might have a low score, while another prediction from a phylogenetic more distant reference species has a higher score. Besides introgressions, many other reasons could lead to such situations, e.g., gene families. 

For me, it seems reasonable to choose the prediction with highest score (=conservation). It has a historical background, when we only used score for sorting predictions, but due to the correlation to other attributes that might be used for sorting it seems to be still valid.

If you use the parameter weight, the attribute sumWeight of the predictions is altered. This attribute can be used for sorting and filtering predictions. However, the weight does not have an influence on the choice of the representative.

Why do you like to have a representative from the phylogenetic closest species?
If you like to analyze synteny, we have implemented SyntenyChecker:
http://www.jstacs.de/index.php/GeMoMa-Docs#Synteny_checker
Maybe the output can be beneficial for you. It returns a table with some standard columns plus one column per reference species. 

best regards, Jens

**Comment by CrawlingSponge** [comment]
Hi, Jens,
Thanks for your proffesional answer, this prediction from different references is very likely inffluenced by the introgression or ILS.

the filter step "GAF" indeed chose the best score of the predictions.

there is still one issue confused me, the predictions from different references (spceices1, species2, species3 and species4) have different exons numbers. how should i solve this problem?


for example, the gene of RPL38, this prediction with 4 exons,
![image](https://user-images.githubusercontent.com/22827591/185335817-f3e0776d-4bc1-413c-8483-7f22ea33eda9.png)

this prediction with 1 exon,
![image](https://user-images.githubusercontent.com/22827591/185335638-e85453c4-21ed-4358-a936-783cfea7775f.png)

yours, sincerely

**Comment by JensKeilwagen** [comment]
Hi,

ce is the number of **c**oding **e**xons (of the prediction)
rce is the number of **r**eference **c**oding **e**xons

In both of your examples ce equals rce.

Introns can be gained or lost. Depending on the phylogenetic distance, this should be rare.

Indeed, the filter in GAF is applied after removing redundancy:
https://github.com/Jstacs/Jstacs/blob/65a454d228c241a759b0a9409819dba89f1448a6/projects/gemoma/GeMoMaAnnotationFilter.java#L551-L570
Hence, alternatives could have a different number of coding exons than the representative. Was this your point?

If I understood you correctly, we only like to have predictions with exactly the same number of ce and rce.
You can tell GeMoMa than gaining or losing an intron is very expensive:
http://www.jstacs.de/index.php/GeMoMa-Docs#GeneModelMapper
Cf. parameter intron-loss-gain-penalty. This might help.

best regards, Jens

**Comment by CrawlingSponge** [comment]
thanks again, Jens
okay, i ll give it a try with a strict value of intron-loss-gain-penalty
