### ISSUE TITLE
GeMoMa expected runtime

### ISSUE THREAD

**Issue by V-JJ** [Jstacs/Jstacs#41]
Hello!

I am trying to run GeMoMa pipeline for the first time using:
1- One target species genome
2- RNAseq data from this species of interest 
2- Annotation from one closely related reference species 

Here (#7) you mentioned that tblastn had some bug that could result in huge run times.  My job has been already running for 5 days on 20 CPUs.
- Do you know if current `tblastn` version have this problem solved. I'm using blast 2.12.0+?
- Is there much difference between `mmseq` results and `tblastn`? 

Thanks in advance,

**Comment by JensKeilwagen** [comment]
Hi VV-j,

thanks a lot for your interest in GeMoMa. 
Currently, we do not use tblastn in GeMoMa in our own studies. Tblastn was the first search algorithm we used in GeMoMa, since mmseqs was much faster and the results were almost identical, we switched to mmseqs by default. Unfortunately, I can't currently say if the bug in tblastn has been fixed. 

best regards, Jens

**Comment by V-JJ** [comment]
Hello!!

Understood, many thanks!
In fact, the runtime is like chalk and cheese between them. Mmseq finished the whole pipeline in 5h, while tblastn 2.12 didn't even manage to finish the job in 5 days.

Best,
