### ISSUE TITLE
AnnotationFinalizer for renaming genes and transcripts

### ISSUE THREAD

**Issue by sjfleck** [Jstacs/Jstacs#45]
Hello,
I'm currently trying to annotate my genome with multiple references. I've used GeMoMa many times before , but this time my goal is to have my own prefix for the genes, transcripts, etc (i.e. Sg_v4.2 at the start of every gene and associated transcript). This is my current command:

java -Xmx64g -jar $GEMOMA/GeMoMa-1.9.jar CLI GeMoMaPipeline \
t=$TARGET o=true p=true \
s=own a=$REFANN0 g=$REFGEN0 \
s=own a=$REFANN1 g=$REFGEN1 \
s=own a=$REFANN2 g=$REFGEN2 \
s=own a=$REFANN3 g=$REFGEN3 \
s=own a=$REFANN4 g=$REFGEN4 \
tblastn=false \
GeMoMa.c=0.4 \
GeMoMa.Score=ReAlign \
AnnotationFinalizer.r=NO \
Extractor.r=true \
Extractor.f=false \
GAF.f="start=='M' and stop=='*' and (isNaN(score) or score/aa>='3.50')" \
outdir=$OUTDIR/gemoma_output threads=12

This results in gene IDs such as "gene_1", but the mRNA IDs still reference the the reference that it was derived from. Is there a method to rename the mRNAs with your own original prefix?

I tried AnnotationFinalizer.r=COMPOSED, but I kept getting errors. I assume I need to use "AnnotationFinalizer.p" as well, but I kept providing names that can't be used. What is meant by "the prefix of the generic name"? 

I can't find clear directions for doing this kind of thing using GeMoMa. Any help would be greatly appreciated. Thanks!

**Comment by JensKeilwagen** [comment]
Hi Steve,

Thanks for using GeMoMa.

If you like to rename genes and transcripts you have to use the parameters from the module AnnotationFinalizer:
http://www.jstacs.de/index.php/GeMoMa-Docs#AnnotationFinalizer
You can either run AnnotationFinalizer on your own or as part of teh GeMoMaPipeline. By default renaming is inactivated. To activate the renaming, you have to set AnnotationFinalizer.r. There are three different options:

- NO: which leads to no renaming
- COMPOSED: which leads to a renaming using some chromosome/contig/... infix
- SIMPLE: which leads to a renaming without using a chromsome/contig/... infix

If you chose any of the options COMPOSED or SIMPLE you have to set further parameters for the renaming, e.g., a prefix. Currently the prefix is limited to `\w+` which is `[a-zA-Z_0-9]+`. Hence, your current prefix is not allowed due to the dot.

Some more information is given in the manual:
http://www.jstacs.de/images/c/c6/GeMoMa-manual.pdf
However, I saw that there are some formating mistakes. I'll change this for the next release.

I hope that helps. Please let me know whether you were successfully or not. If you were not sucessfully, please add the error message for better support.

best regards, Jens

**Comment by sjfleck** [comment]
Jens,
thank you for your quick response. I used a value for AnnotationFinalizer.p without illegal characters and it worked fine. 
-Steve
