### ISSUE TITLE
Exception in thread "main" java.lang.NullPointerException

### ISSUE THREAD

**Issue by joleneyue** [Jstacs/Jstacs#46]
Dear Developer,

thanks a lot for developing this nice software.

i would like to ask you some questions condering my analysis.

i used Tsebra to combine with braker 2 to predict the genes and now i want to use GeMoma to add the UTR on, 

i tested the software with the ./test.sh and it works.

i also used java -jar GeMoMa-1.9.jar CLI ERE m=analysis/Cday10_1.bam 
#this step produce the introns.gff and covergar.bedgragh successfully.

Then when i want to run annotationfinalizer:
java -jar GeMoMa-1.9.jar CLI AnnotationFinalizer u=YES g=analysis/assembly.fasta.PolcaCorrected.FINAL.fasta a=analysis/Helsinki_Plus_Feywei_nonOverlapping_annotation.gff i=analysis/introns.gff c=UNSTRANDED coverage_unstranded=analysis/coverage.bedgraph rename=NO outdir=x

the error occurred:

Exception in thread "main" java.lang.NullPointerException at projects.gemoma.AnnotationFinalizer.read(AnnotationFinalizer.java:517) at projects.gemoma.AnnotationFinalizer.run(AnnotationFinalizer.java:663) at projects.gemoma.AnnotationFinalizer.run(AnnotationFinalizer.java:603) at projects.gemoma.GeMoMaModule.run(GeMoMaModule.java:94) at de.jstacs.tools.ui.cli.CLI.run(CLI.java:426) at projects.gemoma.GeMoMa.main(GeMoMa.java:399)

my gff input file looks like this :

HiC_scaffold_1 AUGUSTUS mRNA 3484 5786 . - . ID=Bpus_H_g1.t1;geneID=Bpus_H_g1 
HiC_scaffold_1 AUGUSTUS exon 3484 3726 1.00 - . Parent=Bpus_H_g1.t1 
HiC_scaffold_1 AUGUSTUS exon 4045 4137 1.00 - . Parent=Bpus_H_g1.t1 
HiC_scaffold_1 AUGUSTUS exon 4373 4502 1.00 - . Parent=Bpus_H_g1.t1 
HiC_scaffold_1 AUGUSTUS exon 4875 4934 1.00 - . Parent=Bpus_H_g1.t1 
HiC_scaffold_1 AUGUSTUS exon 5175 5400 1.00 - . Parent=Bpus_H_g1.t1 
HiC_scaffold_1 AUGUSTUS exon 5582 5786 1.00 - . Parent=Bpus_H_g1.t1 
HiC_scaffold_1 AUGUSTUS CDS 3484 3726 . - 0 Parent=Bpus_H_g1.t1 
HiC_scaffold_1 AUGUSTUS CDS 4045 4137 . - 0 Parent=Bpus_H_g1.t1 
HiC_scaffold_1 AUGUSTUS CDS 4373 4502 . - 1 Parent=Bpus_H_g1.t1

my Java version is 1.8 and my GeMoma version is 1.9

I would like o ask why this happens and how to solve it?

Cheers,
Yuling

**Comment by JensKeilwagen** [comment]
Hi Yuling,

Thanks a lot for your interest in GeMoMa and for reporting this issue.
I just had a quick look into the code:
https://github.com/Jstacs/Jstacs/blob/2c96c5989408b9b724ee37bbde65cc4d50054111/projects/gemoma/AnnotationFinalizer.java#L516-L517

It seems that `f` is `null`. The annotation is read sequentially, cf.
https://github.com/Jstacs/Jstacs/blob/2c96c5989408b9b724ee37bbde65cc4d50054111/projects/gemoma/AnnotationFinalizer.java#L426
and
https://github.com/Jstacs/Jstacs/blob/2c96c5989408b9b724ee37bbde65cc4d50054111/projects/gemoma/AnnotationFinalizer.java#L477

So if a certain level is not provided, line 516 will return `null` and the eror occurs.

Looking at your gff, it seems that you don't have `gene` annotation. At least I only see `mRNA` and `CDS` that is relevant for `AnnotationFinalizer`.

Normally, we use the module `GAF` to combine annotations. `GAF` will also provide `gene` annotation and the result of `GAF` should be fine as input for `AnnotationFinalizer`.

However, I cannot say anything about your project and intention. So I'm not sure how you combine annotations, ...
Nevertheless the problem seems to be the missing `gene` annotation line. 

best regards, Jens

**Comment by joleneyue** [comment]
Dear Jens,

@JensKeilwagen 

Thanks so much for your reply. my input file was produced by annotation tool: TSEBRA :https://github.com/Gaius-Augustus/TSEBRA 

i solved the problem with the help of you suggestions:

i add lines with the third attribute" gene"  lines before "mRNA" lines as it might have to fullfill the sequential order called by the code as you indicated.

the newly modified input file look like this: 

HiC_scaffold_1 AUGUSTUS gene 3484 5786 . - . ID=Bpus_H_g1;geneID=Bpus_H_g1 
HiC_scaffold_1 AUGUSTUS mRNA 3484 5786 . - . ID=Bpus_H_g1.t1;geneID=Bpus_H_g1;Parent=Bpus_H_g1 
HiC_scaffold_1 AUGUSTUS exon 3484 3726 1.00 - . Parent=Bpus_H_g1.t1 
HiC_scaffold_1 AUGUSTUS exon 4045 4137 1.00 - . Parent=Bpus_H_g1.t1 
HiC_scaffold_1 AUGUSTUS exon 4373 4502 1.00 - . Parent=Bpus_H_g1.t1 
HiC_scaffold_1 AUGUSTUS exon 4875 4934 1.00 - . Parent=Bpus_H_g1.t1 
HiC_scaffold_1 AUGUSTUS exon 5175 5400 1.00 - . Parent=Bpus_H_g1.t1 
HiC_scaffold_1 AUGUSTUS exon 5582 5786 1.00 - . Parent=Bpus_H_g1.t1 
HiC_scaffold_1 AUGUSTUS CDS 3484 3726 . - 0 Parent=Bpus_H_g1.t1 
HiC_scaffold_1 AUGUSTUS CDS 4045 4137 . - 0 Parent=Bpus_H_g1.t1

Running gemoma with the modified gff file,  the run was successful.

Cheers,
Yuling
