### ISSUE TITLE
Confuse  about the errors

### ISSUE THREAD

**Issue by Huangyizhong** [Jstacs/Jstacs#5]
Hi,
I have used the GeMoMa to do the prediction of mammalian genome, the codes shown as follows:
GeMoMa=/home/softwares/miniconda3/pkgs/gemoma-1.6.4-0/share/GeMoMa-1.7.1.jar 
genome=/home/bmx01HIFI_v130.fa
nohup java -jar  ${GeMoMa} CLI GeMoMa s=test.bla t=${genome} c=cds-parts.fasta i=introns.gff &
It seems work well. but there is one problem that I am very confused:
"java.lang.IllegalArgumentException: There is no sequence with sequence ID 347 in the target genome." 
I only have 20 chrosomes, why does this problem  come out?
"genome parts: 20    [chrY, chr9, chr7, chrX, chr8, chr5, chr6, chr10, chr3, chr11, chr4, chr1, chr12, chr13, chr2, chr18, chr14, chr15, chr16, chr17]"
I am very confused about it
Need help!
Thanks so much!
Yizhong Huang

**Comment by JensKeilwagen** [comment]
Hi Yizhong Huang,

thanks a lot for your email. Based on the limited information, I can currently not make a good guess.
I assume that either your intron file (introns.gff) or your search result (test.bla) might contain this sequence ID.
If this does not help, please provide the stack trace allowing me to locate the line of code that throws this Exception.

best regards, Jens

**Comment by JensKeilwagen** [comment]
I had a deeper look into the code and I think I could identify the line of code that throws this IllegalArgumentException. It is in the method addHit that parses the search results. The exception is thrown because your search results contains (at least) one match on a contig that is not given in the target genome. You probably have several versions of your target genome. Maybe you have use one version for the search and another for the the GeMoMa run. 
The resaon for different genome versions could be for instance additional polishing steps, filtering of spurious contigs or renaming of contigs.
