### ISSUE TITLE
GeMoMa gives me multiple genes with exact same coordinates

### ISSUE THREAD

**Issue by aseetharam** [Jstacs/Jstacs#55]
Hi, 
Thanks very much for this program. I've a strange problem: I used mikado transcripts and a close relative to annotate a genome, but unfortunately, I get multiple genes for the exact same location, sometimes with multiple isoforms for each locus!
Why would this be happening? I also quickly checked if there are slightly off starts and stops, I did notice some, but didn't extensively search for them.

```
$ awk 'BEGIN{OFS=FS="\t"} !/^#/ && $3=="gene"'  gemoma_output_v1/final_annotation.gff |\
      cut -f 1-7 |\
      sort |\
      uniq -d |\
      wc -l
 844
```
Do you know why this is happening? The `o=true` or `o=false` didn't change this much.

Thanks,

**Comment by aseetharam** [comment]
I also noticed 2 `CDS` features, exact same start and stops but on the opposite strand!  This shouldn't happen, right? I wonder if I messed up something big.
My BUSCO scores are phenomenal, almost match the genome BUSCO, and the total number of genes is also within acceptable range - just these few things are concerning. 
Thanks for any input you can provide!

**Comment by JensKeilwagen** [comment]
Hi Arun,

thanks alot for your interest in GeMoMa.

GeMoMa allows nested genes, i.e., a gene within another gene (cf. https://en.wikipedia.org/wiki/Nested_gene). Nested genes can be located on the same or on the opposite strand. If full-length genes (i.e. genes with start and stop codon) are located on the opposite strand, they should not have the same start and stop. The reason is quite simple: if you compute the reverse complement of the start codon ATG, you receive CAT which is not a stop codon. In contrast to the outer borders, inner borders can be identical on both strand, i.e., an internal exon of a multi-exon gene has an acceptor splice site upstream and a donor splice site downstream. If the adjacent dinucleotides are not the conserved dinucleotides, it could happend that the exon is used on both strands for different genes. However, it would be good to see an example.

The parameter o just states that the indiviual predictions of different reference species are returned. By default (o=false) the indiviual predictions are not returned and the only the combined prediction from the module GAF is returned. If you set o=true, both the individual predictions and the combined predictions are return. In this case, you received multiple individual output files.

It would be good to have more information as for instance an example of those genes on opposite strands with same borders and a statistic how often this occurs. Have you checked whether such overlapping genes on opposite strands also occur in the reference annotation?

Best regards, Jens

**Comment by aseetharam** [comment]
Thank you so much for the prompt reply! 
I understand that nested genes can lead to these situations, but I don't think that's the case here.
Please take a look at these four genes in the same spot:
![image](https://github.com/Jstacs/Jstacs/assets/4835524/69843288-937d-4976-b331-bc0842b3beff)
In the browser, they appear like this:
![image](https://github.com/Jstacs/Jstacs/assets/4835524/37b706f8-d024-4fe1-a4d7-14cb09c7caa7)
(two on plus and two on minus strand)
And weirdly, the simple reason of start codon is not true in this case. Two genes actually end with ATG!
![image](https://github.com/Jstacs/Jstacs/assets/4835524/f24ce360-5ac2-44c4-b6b6-d75175db7454)
Here are the attributes for those features:
![image](https://github.com/Jstacs/Jstacs/assets/4835524/fdc319d3-67f3-40e8-81d1-b4614a2b8d37)

Is this due to some kind of option I used while merging?

```bash
java -Xmx100g -Djava.io.tmpdir=$TMPDIR -jar ${scripts}/GeMoMa-1.9.jar CLI GeMoMaPipeline \
    t=$genome \
    s=own i=sb a=${sorghumGFF} g=${sorghumFa} w=0.5 \
    s=own i=bz a=${maize1GFF3} g=${maize1} w=0.5 \
    s=own i=cz a=${maize2GFF3} g=${maize2} w=0.5 \
    ID=braker e=$braker weight=0.5 \
    ID=mikado e=$mikado weight=0.9 \
    r=MAPPED ERE.m=${bam} ERE.u=false ERE.s=FR_UNSTRANDED ERE.f=YES \
    d=DENOISE \
    Extractor.r=true \
    GAF.f="start=='M' and stop=='*' and score/aa>=3" \
    AnnotationFinalizer.u=YES \
    AnnotationFinalizer.r=SIMPLE AnnotationFinalizer.p=${name} \
    AnnotationFinalizer.n=true \
    sc=false o=false p=true pc=true pgr=false threads=$cpus outdir=${dir} \
    GeMoMa.v=true
```
I appreciate your thoughts on this and any insights that might help resolve these gene models. Thanks again for your kind reply!

**Comment by aseetharam** [comment]
ugh, sorry, forgot to follow up on the identical exons on opposite strands:
![image](https://github.com/Jstacs/Jstacs/assets/4835524/1b89ceac-ce30-460a-bd05-0dd907ab4997)
I think the issue here was that this exon was fragmented in the reference genome I used for annotation, so once I incorporated additional evidence, it went away. I wonder if there is a switch I could enable to keep only those with valid intron/exon boundaries.
![image](https://github.com/Jstacs/Jstacs/assets/4835524/b5a7036c-56c5-466d-a58c-d99e1026c14f)

**Comment by JensKeilwagen** [comment]
Hi Arun,

Thanks a lot for the additional information.

I have to admit that this is a little confusing. There should be no two genes on the same strand with the same exon-intron and start-stop boundaries of the coding sequence. In your case, all genes have the attribute ce=1 indicating that there is only on coding exon. In contrast, the second image shows some introns. Hence, I assume that the coding part is different and only the prediction of the UTR leads to identical boundaries of the mRNAs. Two additional hints are the lines for UTRs in your first image and the start/end of the mRNA that is not matching the expected codons.

Initially, GeMoMa only predicts CDS. The prediction of the UTRs is quite simple and based on the coverage from the transcriptome data. the CDS is extended as long as coverage supports this. (We also allow to use introns in the UTR.)

If some genes are located close to each other in the genome, it could happen that the UTRs are overlapping and hence the covered region harbors multiple genes. In this case, the UTR could be predicted too long and the mRNA seem to be identical. In case of unstranded transcriptome data, this could lead to the same genes boundaries for gnes from opposite strand.

I think this could be the cases here.

We thought about this problem some weeks ago, but did not manage to alter the code yet. One idea could be that the UTR could be extended at most until the next gene. This is a simple solution, but it prevents from getting the same gene boundaries for independent genes.

It would be great:
1. if you could check whether the CDS is different for those 4 genes.
2. if you provide the GAF result and the RNA evidence for this specific region as well as the sequence to us as a minimal example. We could use this as test case for an improved UTR prediction.

Best regards, Jens

**Comment by JensKeilwagen** [comment]
Hi Arun,
I have slightly edited my comment to make things more clear.
Any news from your side? Could you provide the full lines of the GFF for the CDS of these 4 genes.
Would you also provide a minimal example for testing purpose?

best regards, Jens
