### ISSUE TITLE
Renaming the GeMoMa output annotation file.

### ISSUE THREAD

**Issue by ShakNat** [Jstacs/Jstacs#62]
Hi. Thank you for this useful tool! I got my final_annotation.gff file. I had a quick question. The gene IDs and parent fields in the final annotation file are named based on the reference genome's gene IDs. I would however like to have the gene ID and parent fields to contain the names of my query genome's gene IDs for further processing of the file. Can you please let me know how this can be done? Thank you!

**Comment by JensKeilwagen** [comment]
Hi Shakunthala,

Thanks a lot for your interest in GeMoMa.

The module AnnotationFinalizer that is integrated in the GeMoMaPipeline allows to rename the predictions. Please check the parameters AnnotationFinalizer.r and following lines at http://www.jstacs.de/index.php/GeMoMa-Docs#GeMoMa_pipeline
If you set AnnotationFinalizer.n=false it renames the ID instead of adding an additional attribute denoted "Name". This is probably the option you like to have.

best regards, Jens

**Comment by JensKeilwagen** [comment]
Hi Shakunthala,
Of course, you have to set the parameter AnnotationFinalizer.p. I would recommend to use something that is related to your species. For Arabidopsis, AT was used in the official annotation, but I would try to avoid this to avoid confusion between the official and your annotation.

>I want the IDs and the parent fields in the Arabidopsis GFF file to have the same Gene IDs as in the assembly file of Arabidopsis like AT1G00010.1 and so on. How can I match the gene ids of my query's GFF to the query's assembly FASTA file? 

I'm not sure why you like to have the same (=identical gene ID)? As mentioned above I would try to avoid this to avoid potential confusion. If you're interested whether your predictions match some of the official genes, you should compare the offical annotation of Arabidopsis with your annotation. This can be done with the module Analyzer and the using the parameter w=true.

best regards, Jens

**Comment by ShakNat** [comment]
Hi Jens,
Thank you for the clarification. I get it now. My question is answered!
