### ISSUE TITLE
Can a ChIP-seq .bedgraph file (four columns) be used as input for 'labels' in Catchitt

### ISSUE THREAD

**Issue by jcness216** [Jstacs/Jstacs#9]
a line of my file format:
chr2L	9180	9200	0.095
...

I was hoping I could use it (instead of narrow peak 10 column format), but I am getting 'U' for all the labels and so my bedgraph file doesn't seem to work.

This file format is all that is available from the paper--do you have any recommendations? 

(I know this isn't an error question, but I really appreciate the help)

**Comment by jgraux** [comment]
This should work, in general.

I just created a MWE based on our bed line:

File peaks.bed has one line:
`chr2L	9180	9200	0.095`
(just as you posted, but tab-separated)

File chr.fai has one line:
`chr2L	10000	0	0	0`

With those, I called the labels tool:

`java -jar Catchitt-0.1.3.jar labels c=peaks.bed r=peaks.bed  f=chr.fai b=50 rw=50`


As output, I get a file Labels.tsv.gz with mostly "U" labels as you reported. However, there is also one "S" label as would be expected from the input and arguments of the call to labels
```
chr2L	9050	U
chr2L	9100	U
chr2L	9150	S
chr2L	9200	U
chr2L	9250	U
```
because only the 50 bp bin from 9150 to 9200 overlaps with the peak from the bed file.

Could you please check that our output does indeed not contain _any_ labels different from "U"?

Besides, you should make sure that these are indeed peaks from a ChIP-seq experiment (or this input at least makes sense for your use case). 
A peak width of 20 bp seems to be rather narrow.

**Comment by jcness216** [comment]
so the there are no B or S labels ---- my .fai file has chromosome labels: 
`>NC_004354.4 Drosophila melanogaster chromosome X` 
and my chip seq bedgraph file is:
chr2L	9180	9200	0.095
chr2L	9200	9220	0.19
chr2L	9220	9240	0.19
chr2L	9240	9260	0.19
...

is it possible the discrepancy in labeling is the issue?

**Comment by jgraux** [comment]
You .fai file looks more like the header of a FastA file, especially with the line starting with ">".

And yes, the names of the sequences in the .fai must _exactly_ match the sequence identifiers from the bed file.

**Comment by jcness216** [comment]
sorry ! that was the fasta file, the .fai file has labels like this "NC_004354.4"  and NOT labels like  in my chip file. *face palm* thank you
